package manifest

// manifest.go records which source documents the corpus actually holds, in the report's own naming,
// so a faithfulness run can refuse to judge a claim whose cited truth-maker is not present — the
// difference between "we checked and it is not there" (absent) and "we cannot check, the document is
// missing" (unverifiable). A document is identified by a canonical id that both this manifest and a
// claim's cites column use:
//
//	hearing:<date>/<session>          e.g. hearing:2025-02-27/1_yarra-city-council
//	submission:<N>                    e.g. submission:9
//	submission:<N>/attachment-<k>     e.g. submission:19/attachment-1
//	qon:<org>/<date>                  e.g. qon:abc/2025-03-21   (a response to questions on notice)
//
// The set is derived from the filesystem (sources/{hearings,submissions,qon}); MANIFEST.md is a
// committed, human-readable render of it. Scan is the single source of truth; Render and LoadHeld are
// the two views onto it.

import (
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"slices"
	"sort"
	"strconv"
	"strings"
)

// Doc is one held document: its canonical ID and a human label in the report's naming.
type Doc struct {
	ID    string
	Label string
}

// subFile matches a submission filename stem: "09.-ana-a-new-approach-redacted" → N=9, no attachment;
// "33.1-public-galleries-...-redacted" → N=33, attachment 1. The number after the first dot, when a
// digit, is the attachment index.
var subFile = regexp.MustCompile(`^(\d+)\.(\d*)`)

// qonFile matches a QoN-response filename stem "<org>-<YYYY-MM-DD>".
var qonFile = regexp.MustCompile(`^(.+)-(\d{4}-\d{2}-\d{2})$`)

// Scan walks a sources root and returns every held document, sorted by ID. Missing subdirectories are
// simply absent from the result — a corpus without QoN responses yields no qon: ids.
func Scan(root string) ([]Doc, error) {
	var docs []Doc
	add := func(d Doc) { docs = append(docs, d) }

	// Hearings: sources/hearings/<date>/<session>.txt
	hearings := filepath.Join(root, "hearings")
	_ = filepath.WalkDir(hearings, func(p string, d os.DirEntry, err error) error {
		if err != nil || d.IsDir() || !strings.HasSuffix(p, ".txt") {
			return nil
		}
		date := filepath.Base(filepath.Dir(p))
		session := strings.TrimSuffix(filepath.Base(p), ".txt")
		add(Doc{ID: "hearing:" + date + "/" + session, Label: "Hearing " + date + " — " + prettySession(session)})
		return nil
	})

	// Submissions: sources/submissions/<N>[.k]-<org>.txt
	subs := filepath.Join(root, "submissions")
	entries, _ := os.ReadDir(subs)
	for _, e := range entries {
		name := e.Name()
		if e.IsDir() || !strings.HasSuffix(name, ".txt") {
			continue
		}
		stem := strings.TrimSuffix(name, ".txt")
		m := subFile.FindStringSubmatch(stem)
		if m == nil {
			continue
		}
		n, _ := strconv.Atoi(m[1])
		org := prettyOrg(stem)
		if m[2] != "" { // attachment
			k, _ := strconv.Atoi(m[2])
			add(Doc{ID: fmt.Sprintf("submission:%d/attachment-%d", n, k),
				Label: fmt.Sprintf("Submission %d Attachment %d — %s", n, k, org)})
		} else {
			add(Doc{ID: fmt.Sprintf("submission:%d", n), Label: fmt.Sprintf("Submission %d — %s", n, org)})
		}
	}

	// QoN responses: sources/qon/<org>-<date>.txt
	qon := filepath.Join(root, "qon")
	qentries, _ := os.ReadDir(qon)
	for _, e := range qentries {
		name := e.Name()
		if e.IsDir() || !strings.HasSuffix(name, ".txt") {
			continue
		}
		stem := strings.TrimSuffix(name, ".txt")
		if m := qonFile.FindStringSubmatch(stem); m != nil {
			org := strings.ToUpper(m[1])
			add(Doc{ID: "qon:" + m[1] + "/" + m[2], Label: "QoN response — " + org + ", " + m[2]})
		}
	}

	sort.Slice(docs, func(i, j int) bool { return docs[i].ID < docs[j].ID })
	return docs, nil
}

// Held returns the set of document ids in docs, for membership checks.
func Held(docs []Doc) map[string]bool {
	set := make(map[string]bool, len(docs))
	for _, d := range docs {
		set[d.ID] = true
	}
	return set
}

// Render produces the committed MANIFEST.md: a heading, a note, then one bullet per document with the
// canonical id in backticks (so LoadHeld can parse it back) and the report-naming label.
func Render(docs []Doc) string {
	var b strings.Builder
	b.WriteString("# Corpus manifest — documents held under sources/\n\n")
	b.WriteString("Every source document the corpus holds, in the report's own naming. The backticked id is\n")
	b.WriteString("canonical: a claim's `cites` column names the documents a finding rests on with these ids, and\n")
	b.WriteString("a faithfulness run marks a claim `unverifiable` (no model call) when a cited id is not listed\n")
	b.WriteString("here. Generated by `assay -make-manifest sources/`; regenerate after fetching new documents.\n\n")
	groups := []struct {
		prefix, title string
	}{{"hearing:", "Hearings"}, {"submission:", "Submissions"}, {"qon:", "Responses to questions on notice"}}
	for _, g := range groups {
		var lines []string
		for _, d := range docs {
			if strings.HasPrefix(d.ID, g.prefix) {
				lines = append(lines, fmt.Sprintf("- `%s` — %s", d.ID, d.Label))
			}
		}
		if len(lines) == 0 {
			continue
		}
		fmt.Fprintf(&b, "## %s (%d)\n\n%s\n\n", g.title, len(lines), strings.Join(lines, "\n"))
	}
	return strings.TrimRight(b.String(), "\n") + "\n"
}

// docIDLine pulls the backticked canonical id from a MANIFEST.md bullet.
var docIDLine = regexp.MustCompile("^- `([^`]+)`")

// LoadHeld parses the held document ids from a MANIFEST.md. A missing file yields an empty set and no
// error — a run with no manifest simply performs no cited-document check.
func LoadHeld(path string) (map[string]bool, error) {
	set := map[string]bool{}
	data, err := os.ReadFile(path)
	if err != nil {
		if os.IsNotExist(err) {
			return set, nil
		}
		return nil, err
	}
	for ln := range strings.SplitSeq(string(data), "\n") {
		if m := docIDLine.FindStringSubmatch(strings.TrimSpace(ln)); m != nil {
			set[m[1]] = true
		}
	}
	return set, nil
}

// LoadLabels parses a MANIFEST.md into a map from canonical document id to the witness/author name a
// quote's provenance line shows. The name is the LAST " — "-separated segment of the bullet — the
// organisation or witness — so `- ` + "`hearing:…`" + ` — Hearing 2025-03-13 — Public Galleries …`
// yields "Public Galleries …". A missing file yields an empty map and no error, matching LoadHeld.
func LoadLabels(path string) (map[string]string, error) {
	labels := map[string]string{}
	data, err := os.ReadFile(path)
	if err != nil {
		if os.IsNotExist(err) {
			return labels, nil
		}
		return nil, err
	}
	for ln := range strings.SplitSeq(string(data), "\n") {
		ln = strings.TrimSpace(ln)
		m := docIDLine.FindStringSubmatch(ln)
		if m == nil {
			continue
		}
		if segs := strings.Split(ln, " — "); len(segs) >= 2 {
			labels[m[1]] = strings.TrimSpace(segs[len(segs)-1])
		}
	}
	return labels, nil
}

// reportOffsetLine and sectionEntryLine parse the report-link resolution block a report manifest may
// carry: the printed→PDF page offset, and a name→printed-page table so a claim citing a NAMED section
// ("§Executive summary") deep-links to a page the code does not hold. Neither shape starts with "- `",
// so LoadHeld and LoadLabels never mistake a section row for a held document.
var (
	reportOffsetLine = regexp.MustCompile(`^report_page_offset:\s*(-?\d+)$`)
	sectionEntryLine = regexp.MustCompile(`^\s+(.+?):\s*(\d+)\s*$`)
	singleSourceLine = regexp.MustCompile(`^single_source:\s*true\s*$`)
	reportEntryLine  = regexp.MustCompile(`^- file:\s*(.+)$`)
	reportKeyLine    = regexp.MustCompile(`^(file|offset|prefixes):\s*(.*)$`)
)

// LoadSingleSource reports the manifest's `single_source: true` declaration — a corpus that holds the
// report itself as its only source, so the only automated check is internal consistency and there is no
// second document a claim could be corroborated against. It changes what a leaf `absent` means: not "no
// held source carries this" (a grounding miss) but "said once in the report, not repeated elsewhere",
// which the tree renders `uncorroborated` and derives as weakened, not failed. A missing manifest or an
// absent line yields false, no error.
func LoadSingleSource(path string) (bool, error) {
	data, err := os.ReadFile(path)
	if err != nil {
		if os.IsNotExist(err) {
			return false, nil
		}
		return false, err
	}
	for ln := range strings.SplitSeq(string(data), "\n") {
		if singleSourceLine.MatchString(strings.TrimSpace(ln)) {
			return true, nil
		}
	}
	return false, nil
}

// LoadReportLinks reads the review page's report-link rules from a MANIFEST.md so they live in the
// manifest, not the code (spec/SERVE.md): `report_page_offset:` (the printed→PDF offset, 0 when
// absent — a report whose printed page equals its PDF page) and a `sections:` table mapping a named
// section heading to its printed page (empty when absent). A numbered §-ref carries its own page and
// needs no table; a named one is looked up here. A missing manifest yields the zero offset and an
// empty table, no error.
func LoadReportLinks(path string) (offset int, sections map[string]int, err error) {
	sections = map[string]int{}
	data, err := os.ReadFile(path)
	if err != nil {
		if os.IsNotExist(err) {
			return 0, sections, nil
		}
		return 0, nil, err
	}
	inSections := false
	for _, ln := range strings.Split(string(data), "\n") {
		if m := reportOffsetLine.FindStringSubmatch(strings.TrimSpace(ln)); m != nil {
			offset, _ = strconv.Atoi(m[1])
			inSections = false
			continue
		}
		if strings.TrimSpace(ln) == "sections:" {
			inSections = true
			continue
		}
		if inSections {
			if m := sectionEntryLine.FindStringSubmatch(ln); m != nil {
				n, _ := strconv.Atoi(m[2])
				sections[strings.TrimSpace(m[1])] = n
				continue
			}
			if strings.TrimSpace(ln) != "" {
				inSections = false // a non-indented, non-empty line closes the block
			}
		}
	}
	return offset, sections, nil
}

// Report is one report excerpt the corpus holds as a source: the PDF filename a claim's report
// deep-link opens, the printed→PDF page `Offset` applied to that claim's cited page, the named-section
// →printed-page `Sections` table a named §-ref resolves against, and the claim-id `Prefixes` whose
// leaves route to this excerpt. `Prefixes` empty claims every leaf — the single-report corpus, where
// there is only one PDF to open. A corpus decomposed from two report excerpts (spec/SERVE.md § Multiple
// report excerpts) carries one Report per excerpt, and `ReportFor` sends each leaf to its own.
type Report struct {
	File     string
	Offset   int
	Sections map[string]int
	Prefixes []string
}

// LoadReports reads the review page's report-link rules (spec/SERVE.md) as one Report per held excerpt.
// Two manifest shapes yield the same result. The flat single-report form (`report_page_offset:` plus a
// top-level `sections:` table) produces one Report named report.pdf with no `Prefixes`, so it claims
// every leaf — the shape every existing corpus uses, unchanged. The multi-report `reports:` list
// produces one Report per entry, each with its own `file:`, `offset:`, `prefixes:` and `sections:`; a
// `reports:` list present overrides the flat keys. A missing manifest yields one zero-offset report.pdf,
// so a corpus with no report-link rules still links its report at the printed page.
func LoadReports(path string) ([]Report, error) {
	data, err := os.ReadFile(path)
	if err != nil {
		if os.IsNotExist(err) {
			return []Report{{File: "report.pdf", Sections: map[string]int{}}}, nil
		}
		return nil, err
	}
	if reports, ok := parseReportsList(strings.Split(string(data), "\n")); ok {
		return reports, nil
	}
	offset, sections, err := LoadReportLinks(path)
	if err != nil {
		return nil, err
	}
	return []Report{{File: "report.pdf", Offset: offset, Sections: sections}}, nil
}

// parseReportsList parses a `reports:` block into one Report per `- file:` entry, its `offset:`,
// `prefixes:` and nested `sections:` filling that entry until the next entry or the block's end. ok is
// false when no `reports:` block is present, so LoadReports falls back to the flat single-report keys.
// A line at column 0 ends the block — the report-link rules are the manifest's last section, and a
// dedented key (e.g. a later top-level directive) is not part of the list.
func parseReportsList(lines []string) ([]Report, bool) {
	start := -1
	for i, ln := range lines {
		if strings.TrimSpace(ln) == "reports:" {
			start = i
			break
		}
	}
	if start < 0 {
		return nil, false
	}
	var reports []Report
	ci := -1
	inSections := false
	for _, ln := range lines[start+1:] {
		trimmed := strings.TrimSpace(ln)
		if trimmed == "" {
			continue
		}
		if m := reportEntryLine.FindStringSubmatch(trimmed); m != nil {
			reports = append(reports, Report{File: strings.TrimSpace(m[1]), Sections: map[string]int{}})
			ci = len(reports) - 1
			inSections = false
			continue
		}
		if ci < 0 {
			break // a line before the first "- file:" — the block has not started as a list
		}
		if len(ln) == len(trimmed) {
			break // dedented to column 0: the reports block is over
		}
		if trimmed == "sections:" {
			inSections = true
			continue
		}
		if m := reportKeyLine.FindStringSubmatch(trimmed); m != nil {
			inSections = false
			switch m[1] {
			case "file":
				reports[ci].File = strings.TrimSpace(m[2])
			case "offset":
				reports[ci].Offset, _ = strconv.Atoi(strings.TrimSpace(m[2]))
			case "prefixes":
				reports[ci].Prefixes = strings.Fields(m[2])
			}
			continue
		}
		if inSections {
			if sm := sectionEntryLine.FindStringSubmatch(ln); sm != nil {
				n, _ := strconv.Atoi(sm[2])
				reports[ci].Sections[strings.TrimSpace(sm[1])] = n
			}
		}
	}
	if len(reports) == 0 {
		return nil, false
	}
	return reports, true
}

// ReportFor picks the report a claim leaf's deep-link opens, by the alphabetic prefix of its claim id
// (`SB6` → "SB", `EP8` → "EP"). A report whose `Prefixes` lists that prefix wins; a report with no
// `Prefixes` (a single-report corpus) matches every id. ok is false when a multi-report corpus has no
// report claiming the prefix — the ref is then left unlinked rather than pointed at the wrong PDF.
func ReportFor(reports []Report, claimID string) (Report, bool) {
	prefix := idPrefix(claimID)
	fallback := -1
	for i := range reports {
		if len(reports[i].Prefixes) == 0 {
			fallback = i
			continue
		}
		if slices.Contains(reports[i].Prefixes, prefix) {
			return reports[i], true
		}
	}
	if fallback >= 0 {
		return reports[fallback], true
	}
	return Report{}, false
}

// idPrefix returns a claim id's leading non-digit run — the alphabetic prefix a Report's `Prefixes`
// list keys on. "SB6" → "SB", "EP12" → "EP", "" → "".
func idPrefix(id string) string {
	i := 0
	for i < len(id) && !('0' <= id[i] && id[i] <= '9') {
		i++
	}
	return id[:i]
}

// CanonicalDoc maps a retrieval passage id (minted by internal/retrieve) back to the canonical
// document id this manifest uses, plus a human locator. The three passage shapes and their canonical
// forms — the inverse of Scan's id construction, so a resolved doc id is exactly what LoadHeld/
// LoadLabels key on:
//
//	"<date>/<session>#t<n>"   → "hearing:<date>/<session>",              locator "line <n>"
//	"submission-<num>#p<n>"   → "submission:<N>[/attachment-<k>]",       locator "p.<n>"   (num "09" or "09.1")
//	"qon-<org>-<date>#p<n>"   → "qon:<org>/<date>",                      locator "p.<n>"
//	"<excerpt>#p<page>#<n>"   → the excerpt's PDF (from `reports`),       locator "p.<page>"
//
// A report passage id carries a SECOND "#" (the page then the paragraph ordinal), which is what tells
// it from the single-"#" hearing/submission/qon shapes. Its base is the excerpt file stem — "report",
// "report-productivity" — and `reports` (the manifest's `reports:` list) maps that stem to its PDF; a
// stem no entry names falls back to "<stem>.pdf", so a flat single-report corpus with no list still
// resolves "report" → "report.pdf". ok is false when the id matches none of these shapes; a `#p<n>`
// is a paragraph ordinal and a `#t<n>` a speaker-turn ordinal, not a PDF page — the locator wording
// follows the report's own "page or transcript line" naming, not the ordinal's kind.
func CanonicalDoc(pid string, reports []Report) (docID, locator string, ok bool) {
	base, frag, hasFrag := strings.Cut(pid, "#")
	if !hasFrag || base == "" || frag == "" {
		return "", "", false
	}
	switch {
	case strings.HasPrefix(base, "submission-"):
		whole, att, _ := strings.Cut(strings.TrimPrefix(base, "submission-"), ".")
		n, err := strconv.Atoi(whole)
		if err != nil {
			return "", "", false
		}
		docID = fmt.Sprintf("submission:%d", n)
		if att != "" {
			k, err := strconv.Atoi(att)
			if err != nil {
				return "", "", false
			}
			docID = fmt.Sprintf("submission:%d/attachment-%d", n, k)
		}
		return docID, "p." + strings.TrimPrefix(frag, "p"), true
	case strings.HasPrefix(base, "qon-"):
		m := qonFile.FindStringSubmatch(strings.TrimPrefix(base, "qon-"))
		if m == nil {
			return "", "", false
		}
		return "qon:" + m[1] + "/" + m[2], "p." + strings.TrimPrefix(frag, "p"), true
	case strings.HasPrefix(base, "leaderboards/"):
		// A benchmark-leaderboard capture: "leaderboards/<stem>#p<n>" → the held id `leaderboards/<stem>.txt`
		// (the manifest registers each capture by its extracted .txt). The paragraph ordinal is the locator.
		return base + ".txt", "p." + strings.TrimPrefix(frag, "p"), true
	case strings.ContainsRune(frag, '#'):
		// A report excerpt as its own source: "<excerpt>#p<page>#<n>" → the excerpt's PDF at the printed
		// page. The paragraph index after the page is provenance-irrelevant, so the locator is the page
		// alone; the excerpt stem is resolved to its PDF through the manifest's reports list.
		page, _, _ := strings.Cut(frag, "#")
		return reportPDF(base, reports), "p." + strings.TrimPrefix(page, "p"), true
	default:
		// Hearing: "<date>/<session>#t<n>" — the only shape carrying a "/" in its base and a "t" turn.
		if strings.ContainsRune(base, '/') && strings.HasPrefix(frag, "t") {
			return "hearing:" + base, "line " + strings.TrimPrefix(frag, "t"), true
		}
		return "", "", false
	}
}

// reportPDF resolves a report-excerpt id base (its file stem, e.g. "report-productivity") to the PDF
// filename a claim's deep-link opens, by matching the stem against `reports` (a report's File minus its
// extension). No entry matches — a flat single-report corpus loads no list, or the stem is unknown —
// falls back to "<base>.pdf", the naming convention the excerpts follow, so "report" resolves to
// "report.pdf" with or without a list.
func reportPDF(base string, reports []Report) string {
	for _, r := range reports {
		if strings.TrimSuffix(r.File, filepath.Ext(r.File)) == base {
			return r.File
		}
	}
	return base + ".pdf"
}

func prettySession(stem string) string {
	// "1_yarra-city-council" → "Yarra City Council"
	if i := strings.Index(stem, "_"); i >= 0 {
		stem = stem[i+1:]
	}
	return titleWords(stem)
}

func prettyOrg(stem string) string {
	// "09.-ana-a-new-approach-redacted" → "Ana A New Approach"
	rest := subFile.ReplaceAllString(stem, "")
	rest = strings.TrimLeft(rest, ".-")
	rest = strings.TrimSuffix(strings.TrimSuffix(rest, "_redacted"), "-redacted")
	return titleWords(rest)
}

func titleWords(s string) string {
	s = strings.ReplaceAll(strings.ReplaceAll(s, "-", " "), "_", " ")
	fields := strings.Fields(s)
	for i, w := range fields {
		fields[i] = strings.ToUpper(w[:1]) + w[1:]
	}
	return strings.Join(fields, " ")
}
