package manifest

// manifest.go records which source documents the corpus actually holds, in the report's own naming,
// so a faithfulness run can refuse to judge a claim whose cited truth-maker is not present — the
// difference between "we checked and it is not there" (absent) and "we cannot check, the document is
// missing" (unverifiable). A document is identified by a canonical id that both this manifest and a
// claim's cites column use:
//
//	hearing:<date>/<session>          e.g. hearing:2025-02-27/1_yarra-city-council
//	submission:<N>                    e.g. submission:9
//	submission:<N>/attachment-<k>     e.g. submission:19/attachment-1
//	qon:<org>/<date>                  e.g. qon:abc/2025-03-21   (a response to questions on notice)
//
// The set is derived from the filesystem (sources/{hearings,submissions,qon}); MANIFEST.md is a
// committed, human-readable render of it. Scan is the single source of truth; Render and LoadHeld are
// the two views onto it.

import (
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"sort"
	"strconv"
	"strings"
)

// Doc is one held document: its canonical ID and a human label in the report's naming.
type Doc struct {
	ID    string
	Label string
}

// subFile matches a submission filename stem: "09.-ana-a-new-approach-redacted" → N=9, no attachment;
// "33.1-public-galleries-...-redacted" → N=33, attachment 1. The number after the first dot, when a
// digit, is the attachment index.
var subFile = regexp.MustCompile(`^(\d+)\.(\d*)`)

// qonFile matches a QoN-response filename stem "<org>-<YYYY-MM-DD>".
var qonFile = regexp.MustCompile(`^(.+)-(\d{4}-\d{2}-\d{2})$`)

// Scan walks a sources root and returns every held document, sorted by ID. Missing subdirectories are
// simply absent from the result — a corpus without QoN responses yields no qon: ids.
func Scan(root string) ([]Doc, error) {
	var docs []Doc
	add := func(d Doc) { docs = append(docs, d) }

	// Hearings: sources/hearings/<date>/<session>.txt
	hearings := filepath.Join(root, "hearings")
	_ = filepath.WalkDir(hearings, func(p string, d os.DirEntry, err error) error {
		if err != nil || d.IsDir() || !strings.HasSuffix(p, ".txt") {
			return nil
		}
		date := filepath.Base(filepath.Dir(p))
		session := strings.TrimSuffix(filepath.Base(p), ".txt")
		add(Doc{ID: "hearing:" + date + "/" + session, Label: "Hearing " + date + " — " + prettySession(session)})
		return nil
	})

	// Submissions: sources/submissions/<N>[.k]-<org>.txt
	subs := filepath.Join(root, "submissions")
	entries, _ := os.ReadDir(subs)
	for _, e := range entries {
		name := e.Name()
		if e.IsDir() || !strings.HasSuffix(name, ".txt") {
			continue
		}
		stem := strings.TrimSuffix(name, ".txt")
		m := subFile.FindStringSubmatch(stem)
		if m == nil {
			continue
		}
		n, _ := strconv.Atoi(m[1])
		org := prettyOrg(stem)
		if m[2] != "" { // attachment
			k, _ := strconv.Atoi(m[2])
			add(Doc{ID: fmt.Sprintf("submission:%d/attachment-%d", n, k),
				Label: fmt.Sprintf("Submission %d Attachment %d — %s", n, k, org)})
		} else {
			add(Doc{ID: fmt.Sprintf("submission:%d", n), Label: fmt.Sprintf("Submission %d — %s", n, org)})
		}
	}

	// QoN responses: sources/qon/<org>-<date>.txt
	qon := filepath.Join(root, "qon")
	qentries, _ := os.ReadDir(qon)
	for _, e := range qentries {
		name := e.Name()
		if e.IsDir() || !strings.HasSuffix(name, ".txt") {
			continue
		}
		stem := strings.TrimSuffix(name, ".txt")
		if m := qonFile.FindStringSubmatch(stem); m != nil {
			org := strings.ToUpper(m[1])
			add(Doc{ID: "qon:" + m[1] + "/" + m[2], Label: "QoN response — " + org + ", " + m[2]})
		}
	}

	sort.Slice(docs, func(i, j int) bool { return docs[i].ID < docs[j].ID })
	return docs, nil
}

// Held returns the set of document ids in docs, for membership checks.
func Held(docs []Doc) map[string]bool {
	set := make(map[string]bool, len(docs))
	for _, d := range docs {
		set[d.ID] = true
	}
	return set
}

// Render produces the committed MANIFEST.md: a heading, a note, then one bullet per document with the
// canonical id in backticks (so LoadHeld can parse it back) and the report-naming label.
func Render(docs []Doc) string {
	var b strings.Builder
	b.WriteString("# Corpus manifest — documents held under sources/\n\n")
	b.WriteString("Every source document the corpus holds, in the report's own naming. The backticked id is\n")
	b.WriteString("canonical: a claim's `cites` column names the documents a finding rests on with these ids, and\n")
	b.WriteString("a faithfulness run marks a claim `unverifiable` (no model call) when a cited id is not listed\n")
	b.WriteString("here. Generated by `assay -make-manifest sources/`; regenerate after fetching new documents.\n\n")
	groups := []struct {
		prefix, title string
	}{{"hearing:", "Hearings"}, {"submission:", "Submissions"}, {"qon:", "Responses to questions on notice"}}
	for _, g := range groups {
		var lines []string
		for _, d := range docs {
			if strings.HasPrefix(d.ID, g.prefix) {
				lines = append(lines, fmt.Sprintf("- `%s` — %s", d.ID, d.Label))
			}
		}
		if len(lines) == 0 {
			continue
		}
		fmt.Fprintf(&b, "## %s (%d)\n\n%s\n\n", g.title, len(lines), strings.Join(lines, "\n"))
	}
	return strings.TrimRight(b.String(), "\n") + "\n"
}

// docIDLine pulls the backticked canonical id from a MANIFEST.md bullet.
var docIDLine = regexp.MustCompile("^- `([^`]+)`")

// LoadHeld parses the held document ids from a MANIFEST.md. A missing file yields an empty set and no
// error — a run with no manifest simply performs no cited-document check.
func LoadHeld(path string) (map[string]bool, error) {
	set := map[string]bool{}
	data, err := os.ReadFile(path)
	if err != nil {
		if os.IsNotExist(err) {
			return set, nil
		}
		return nil, err
	}
	for ln := range strings.SplitSeq(string(data), "\n") {
		if m := docIDLine.FindStringSubmatch(strings.TrimSpace(ln)); m != nil {
			set[m[1]] = true
		}
	}
	return set, nil
}

func prettySession(stem string) string {
	// "1_yarra-city-council" → "Yarra City Council"
	if i := strings.Index(stem, "_"); i >= 0 {
		stem = stem[i+1:]
	}
	return titleWords(stem)
}

func prettyOrg(stem string) string {
	// "09.-ana-a-new-approach-redacted" → "Ana A New Approach"
	rest := subFile.ReplaceAllString(stem, "")
	rest = strings.TrimLeft(rest, ".-")
	rest = strings.TrimSuffix(strings.TrimSuffix(rest, "_redacted"), "-redacted")
	return titleWords(rest)
}

func titleWords(s string) string {
	s = strings.ReplaceAll(strings.ReplaceAll(s, "-", " "), "_", " ")
	fields := strings.Fields(s)
	for i, w := range fields {
		fields[i] = strings.ToUpper(w[:1]) + w[1:]
	}
	return strings.Join(fields, " ")
}
